import express from 'express';
import multer from 'multer';
import crypto from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { del, get, put } from '@vercel/blob';
import { DEFAULT_CONTENT } from './src/data/defaultContent.js';

const app = express();
const root = path.dirname(fileURLToPath(import.meta.url));
const publicDir = path.join(root, 'public');
const adminPassword = String(process.env.ADMIN_PASSWORD || '');
const passwordFromEnv = adminPassword.length >= 12 && !/^replace-with-/i.test(adminPassword) ? adminPassword : '';
const BUILT_IN_PASSWORD_SHA256 = '1f9b10217856ffb8312980b304e03653e008aa7824d96df254fcd4efb3753587';
const expectedPasswordHash = passwordFromEnv ? crypto.createHash('sha256').update(passwordFromEnv).digest('hex') : BUILT_IN_PASSWORD_SHA256;
const secret = crypto.createHash('sha256').update(expectedPasswordHash).digest();
const SESSION_TTL = 7 * 24 * 60 * 60 * 1000;
const CONTENT_PATH = 'cms/content.json';
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 4 * 1024 * 1024 }, fileFilter: (_, file, cb) => cb(null, /^image\/(jpeg|png|webp|gif|avif)$/.test(file.mimetype)) });
const failed = new Map();

function hmac(value) { return crypto.createHmac('sha256', secret).update(value).digest('hex'); }
function cookieMap(header = '') { return Object.fromEntries(header.split(';').map(v => v.trim().split('=')) .filter(([k,v]) => k && v)); }
function sessionPayload(req) { const raw = cookieMap(req.headers.cookie).durga_cms || ''; const [payload, sig] = raw.split('.'); if (!payload || !sig) return null; const a = Buffer.from(sig); const b = Buffer.from(hmac(payload)); if (a.length !== b.length || !crypto.timingSafeEqual(a, b)) return null; const [issued, nonce] = payload.split(':'); if (!issued || !nonce || Date.now() - Number(issued) > SESSION_TTL) return null; return payload; }
function csrfFor(payload) { return hmac(`csrf:${payload}`); }
function authed(req) { return Boolean(sessionPayload(req)); }
function requireAuth(req, res, next) { if (!authed(req)) return res.status(401).json({ error: 'Authentication required' }); next(); }
function validCsrf(req) { const session = sessionPayload(req); const token = req.headers['x-csrf-token']; return Boolean(session && token && token === csrfFor(session)); }
function slugify(v) { return String(v || 'item').toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || `item-${Date.now()}`; }
function validMoney(v) { return v === '' || v == null || /^\d+(\.\d{1,2})?$/.test(String(v).trim()); }
function normalize(c) { const site={...DEFAULT_CONTENT.site,...(c?.site||{})}; site.featuredProductIds=Array.isArray(site.featuredProductIds)?site.featuredProductIds.map(String):[]; site.marqueeItems=Array.isArray(site.marqueeItems)?site.marqueeItems.map(String).filter(Boolean):[]; const products=Array.isArray(c?.products)?c.products.map((p,i)=>({id:slugify(p.id||p.name||`product-${i+1}`),name:String(p.name||'Untitled Product').trim(),category:String(p.category||'Pickles').trim(),size:String(p.size||'').trim(),price:validMoney(p.price)?String(p.price??'').trim():'',mrp:validMoney(p.mrp)?String(p.mrp??'').trim():'',image:String(p.image||''),description:String(p.description||''),featured:Boolean(p.featured),order:Number.isFinite(Number(p.order))?Number(p.order):i})):[]; const gallery=Array.isArray(c?.gallery)?c.gallery.map((g,i)=>({id:slugify(g.id||`gallery-${i+1}`),src:String(g.src||''),label:String(g.label||'Untitled').trim(),type:g.type==='wide'?'wide':'portrait',order:Number.isFinite(Number(g.order))?Number(g.order):i})):[]; site.featuredProductIds=site.featuredProductIds.filter(id=>products.some(p=>p.id===id)); return {site,products,gallery}; }
async function blobContent() { if (!process.env.BLOB_READ_WRITE_TOKEN) return null; const result=await get(CONTENT_PATH,{access:'public'}); if(!result||result.statusCode!==200||!result.stream)return null; return normalize(JSON.parse(await new Response(result.stream).text())); }
async function readContent(){try{return (await blobContent())||normalize(DEFAULT_CONTENT);}catch{return normalize(DEFAULT_CONTENT);}}
async function writeContent(content){if(!process.env.BLOB_READ_WRITE_TOKEN)throw new Error('CMS storage is not configured. Create a Vercel Blob store and add BLOB_READ_WRITE_TOKEN.');await put(CONTENT_PATH,JSON.stringify(normalize(content),null,2),{access:'public',allowOverwrite:true,contentType:'application/json',cacheControlMaxAge:60});}
function setCookie(res,payload){res.setHeader('Set-Cookie',`durga_cms=${payload}.${hmac(payload)}; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=604800`);}
function clearCookie(res){res.setHeader('Set-Cookie','durga_cms=; HttpOnly; Secure; SameSite=Lax; Path=/; Max-Age=0');}
function rateLimited(req){const key=req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown';const now=Date.now();const hits=(failed.get(key)||[]).filter(t=>now-t<600000);failed.set(key,hits);return hits.length>=8;}
function fail(req){const key=req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown';const hits=(failed.get(key)||[]).filter(t=>Date.now()-t<600000);hits.push(Date.now());failed.set(key,hits);}

app.disable('x-powered-by');
app.use(express.json({limit:'12mb'}));
app.use((req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');res.setHeader('X-Frame-Options','DENY');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');res.setHeader('Content-Security-Policy',"default-src 'self'; img-src 'self' data: https:; style-src 'self' 'unsafe-inline'; script-src 'self'; connect-src 'self'; font-src 'self'; frame-ancestors 'none';");if(!['GET','HEAD','OPTIONS'].includes(req.method)&&req.path.startsWith('/api/')&&!req.path.startsWith('/api/auth/login')&&!req.path.startsWith('/api/auth/logout')&&!validCsrf(req))return res.status(403).json({error:'Invalid or expired CSRF token'});next();});
app.get('/api/auth/status',(_,res)=>res.json({configured:true,setupRequired:false,authenticated:false}));
app.post('/api/auth/login',(req,res)=>{if(rateLimited(req))return res.status(429).json({error:'Too many attempts. Try again later.'});const candidate=String(req.body?.password||'');const a=crypto.createHash('sha256').update(candidate).digest();const b=Buffer.from(expectedPasswordHash,'hex');if(a.length!==b.length||!crypto.timingSafeEqual(a,b)){fail(req);return res.status(401).json({error:'Incorrect password'});}const payload=`${Date.now()}:${crypto.randomBytes(16).toString('hex')}`;setCookie(res,payload);res.json({ok:true,csrfToken:csrfFor(payload)});});
app.post('/api/auth/logout',(_,res)=>{clearCookie(res);res.json({ok:true});});
app.get('/api/admin/session',requireAuth,(_,res)=>res.json({ok:true}));
app.get('/api/content',async(_,res)=>{try{res.setHeader('Cache-Control','no-store');res.json(await readContent());}catch{res.status(500).json({error:'Could not load CMS content'});}});
app.get('/api/export',requireAuth,async(_,res)=>{try{res.setHeader('Content-Disposition','attachment; filename=durga-content.json');res.json(await readContent());}catch{res.status(500).json({error:'Could not export CMS content'});}});

app.put('/api/settings',requireAuth,async(req,res)=>{try{const c=await readContent();c.site={...c.site,...req.body};await writeContent(c);res.json(c.site);}catch(e){res.status(503).json({error:e.message});}});
app.post('/api/upload',requireAuth,upload.single('file'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'Choose a supported image under 4 MB.'});if(!process.env.BLOB_READ_WRITE_TOKEN)return res.status(503).json({error:'Vercel Blob storage is not configured.'});const name=req.file.originalname.replace(/[^a-zA-Z0-9._-]/g,'-');const blob=await put(`images/${Date.now()}-${crypto.randomBytes(6).toString('hex')}-${name}`,req.file.buffer,{access:'public',contentType:req.file.mimetype,cacheControlMaxAge:31536000});res.json({url:blob.url,name:req.file.originalname,size:req.file.size});}catch(e){res.status(503).json({error:e.message||'Upload failed'});}});
app.post('/api/products',requireAuth,async(req,res)=>{try{const c=await readContent();if(!validMoney(req.body?.price)||!validMoney(req.body?.mrp))return res.status(400).json({error:'Price and MRP must be numbers with up to two decimals.'});let id=slugify(req.body?.id||req.body?.name||'product'),n=2;while(c.products.some(p=>p.id===id))id=`${slugify(req.body?.name||'product')}-${n++}`;const p={id,name:String(req.body?.name||'Untitled Product'),category:String(req.body?.category||'Pickles'),size:String(req.body?.size||''),price:String(req.body?.price??''),mrp:String(req.body?.mrp??''),image:String(req.body?.image||''),description:String(req.body?.description||''),featured:Boolean(req.body?.featured),order:Number(req.body?.order??c.products.length)};c.products.push(p);if(p.featured)c.site.featuredProductIds.push(p.id);await writeContent(c);res.status(201).json(p);}catch(e){res.status(503).json({error:e.message});}});
app.put('/api/products/:id',requireAuth,async(req,res)=>{try{const c=await readContent(),i=c.products.findIndex(p=>p.id===req.params.id);if(i<0)return res.status(404).json({error:'Product not found'});const old=c.products[i];if(!validMoney(req.body?.price??old.price)||!validMoney(req.body?.mrp??old.mrp))return res.status(400).json({error:'Price and MRP must be numbers with up to two decimals.'});c.products[i]={...old,...req.body,id:slugify(req.body?.id||old.id),price:String(req.body?.price??old.price??''),mrp:String(req.body?.mrp??old.mrp??''),featured:Boolean(req.body?.featured??old.featured),order:Number(req.body?.order??old.order??i)};c.site.featuredProductIds=c.site.featuredProductIds.filter(id=>id!==old.id&&id!==c.products[i].id);if(c.products[i].featured)c.site.featuredProductIds.push(c.products[i].id);await writeContent(c);if(old.image&&old.image!==c.products[i].image&&old.image.includes('.blob.vercel-storage.com'))await del(old.image);res.json(c.products[i]);}catch(e){res.status(503).json({error:e.message});}});
app.delete('/api/products/:id',requireAuth,async(req,res)=>{try{const c=await readContent(),i=c.products.findIndex(p=>p.id===req.params.id);if(i<0)return res.status(404).json({error:'Product not found'});const old=c.products.splice(i,1)[0];c.site.featuredProductIds=c.site.featuredProductIds.filter(id=>id!==old.id);await writeContent(c);if(old.image?.includes('.blob.vercel-storage.com'))await del(old.image);res.json({ok:true});}catch(e){res.status(503).json({error:e.message});}});
app.post('/api/gallery',requireAuth,async(req,res)=>{try{const c=await readContent(),g={id:slugify(req.body?.id||req.body?.label||`gallery-${Date.now()}`),src:String(req.body?.src||''),label:String(req.body?.label||'Untitled'),type:req.body?.type==='wide'?'wide':'portrait',order:Number(req.body?.order??c.gallery.length)};c.gallery.push(g);await writeContent(c);res.status(201).json(g);}catch(e){res.status(503).json({error:e.message});}});
app.put('/api/gallery/:id',requireAuth,async(req,res)=>{try{const c=await readContent(),i=c.gallery.findIndex(g=>g.id===req.params.id);if(i<0)return res.status(404).json({error:'Gallery item not found'});const old=c.gallery[i];c.gallery[i]={...old,...req.body,id:old.id};await writeContent(c);if(old.src!==c.gallery[i].src&&old.src?.includes('.blob.vercel-storage.com'))await del(old.src);res.json(c.gallery[i]);}catch(e){res.status(503).json({error:e.message});}});
app.delete('/api/gallery/:id',requireAuth,async(req,res)=>{try{const c=await readContent(),i=c.gallery.findIndex(g=>g.id===req.params.id);if(i<0)return res.status(404).json({error:'Gallery item not found'});const old=c.gallery.splice(i,1)[0];await writeContent(c);if(old.src?.includes('.blob.vercel-storage.com'))await del(old.src);res.json({ok:true});}catch(e){res.status(503).json({error:e.message});}});
app.post('/api/import',requireAuth,async(req,res)=>{try{if(!req.body?.site||!Array.isArray(req.body?.products)||!Array.isArray(req.body?.gallery))return res.status(400).json({error:'Invalid content backup'});const c=normalize(req.body);await writeContent(c);res.json(c);}catch(e){res.status(503).json({error:e.message});}});

app.get(/.*/,(_,res)=>res.sendFile(path.join(publicDir,'index.html')));
export default app;
