import React,{useState} from 'react';
import { ArrowUpRight, MessageCircle, Phone, MapPin, Send } from 'lucide-react';
import { motion } from 'motion/react';
import Reveal from '../components/Reveal';
import GlowCard from '../components/GlowCard';
import { useContent } from '../context';

export default function Contact(){
  const { site } = useContent(); const [message,setMessage]=useState(''); const submit=e=>{e.preventDefault(); const fd=new FormData(e.currentTarget); const text=`Hello ${site.brandName}, my name is ${fd.get('name')}. ${fd.get('message')}`; window.open(`https://wa.me/${String(site.whatsapp||'').replace(/\D/g,'')}?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer'); setMessage('WhatsApp opened with your enquiry.');};
  return <section className="contact-page-premium"><div className="container"><Reveal><div className="contact-intro"><div><div className="eyebrow-line">CONTACT</div><h1>Let’s talk <em>Durga.</em></h1></div><p>Use the direct details below for product enquiries, availability and business enquiries.</p></div></Reveal><div className="contact-layout-premium"><GlowCard className="contact-info-card"><div className="contact-brand-note"><span>SREE DURGA FOOD PRODUCTS</span><strong>Since 1996</strong></div><div className="contact-info-list"><a href={`tel:+${String(site.phone||'').replace(/\D/g,'')}`}><Phone/><div><small>Phone</small><b>{site.phone}</b></div><ArrowUpRight size={15}/></a><a href={`tel:+${String(site.consumerCare||'').replace(/\D/g,'')}`}><MessageCircle/><div><small>Consumer care</small><b>{site.consumerCare}</b></div><ArrowUpRight size={15}/></a><a href={site.mapUrl} target="_blank" rel="noreferrer"><MapPin/><div><small>Location</small><b>{site.locationLine1}</b></div><ArrowUpRight size={15}/></a></div></GlowCard><motion.form className="enquiry-form-premium" onSubmit={submit} initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.7,delay:.08}}><div className="form-title"><h3>Send an enquiry</h3><span>This form opens WhatsApp with your message.</span></div><div className="form-grid"><label>Name<input name="name" required placeholder="Your name" autoComplete="name"/></label><label>Phone<input name="phone" required placeholder="Your phone number" inputMode="tel" autoComplete="tel"/></label></div><label>Message<textarea name="message" required rows="5" placeholder="What would you like to know?"></textarea></label><button className="btn-premium" type="submit"><Send size={15}/> Continue on WhatsApp</button>{message&&<p className="form-success" role="status">{message}</p>}</motion.form></div></div></section>;
}
