import React,{useEffect,useState} from 'react';
import { Link, NavLink } from 'react-router-dom';
import { Menu, X, MessageCircle, ArrowUpRight, Phone } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import Brand from './Brand';
import MagneticButton from './MagneticButton';
import ScrollProgress from './ScrollProgress';
import { useContent } from '../context';
import { whatsappUrl } from '../lib';

export default function Layout({children}){
  const { site }=useContent(); const [open,setOpen]=useState(false); const nav=[['/','Home'],['/products','Products'],['/gallery','Gallery'],['/contact','Contact']]; const wa=whatsappUrl(site.whatsapp,'Hello Durga Foods, I would like to make an enquiry.');
  useEffect(()=>{document.body.classList.toggle('menu-open',open); return()=>document.body.classList.remove('menu-open')},[open]);
  useEffect(()=>{document.title=site.metaTitle||'Durga Foods — Since 1996'; const meta=document.querySelector('meta[name="description"]'); if(meta) meta.setAttribute('content',site.metaDescription||'');},[site]);
  return <div className="app-shell"><ScrollProgress/><div className="announcement-premium">{site.announcement}</div><header className="site-header-premium"><div className="container nav-inner-premium"><Link to="/" className="brand-link" onClick={()=>setOpen(false)}><Brand/></Link><nav className="desktop-nav-premium" aria-label="Primary navigation">{nav.map(([to,label])=><NavLink key={to} to={to} end={to==='/' } className={({isActive})=>isActive?'active':''}>{label}</NavLink>)}<MagneticButton href={wa} className="nav-order-premium" target="_blank" rel="noreferrer"><MessageCircle size={15}/> Enquire <ArrowUpRight size={14}/></MagneticButton></nav><button className="mobile-menu-premium" onClick={()=>setOpen(v=>!v)} aria-label={open?'Close menu':'Open menu'} aria-expanded={open}>{open?<X size={24}/>:<Menu size={24}/>}</button></div><AnimatePresence initial={false}>{open&&<motion.nav className="mobile-drawer" aria-label="Mobile navigation" initial={{opacity:0,y:-10}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-10}} transition={{duration:.25}}>{nav.map(([to,label])=><NavLink key={to} to={to} end={to==='/' } onClick={()=>setOpen(false)}>{label}<ArrowUpRight size={15}/></NavLink>)}<a className="mobile-order" href={wa} target="_blank" rel="noreferrer"><MessageCircle size={16}/> Enquire on WhatsApp</a></motion.nav>}</AnimatePresence></header>{children}<nav className="mobile-bottom-nav" aria-label="Quick navigation">{nav.map(([to,label])=><NavLink key={to} to={to} end={to==='/' } onClick={()=>setOpen(false)}><span className="mobile-bottom-dot"/>{label}</NavLink>)}</nav><footer className="site-footer-premium"><div className="container footer-top-premium"><div><Brand/><p>{site.footerDescription}<br/>{site.locationLine1}<br/>{site.locationLine2}</p><div className="footer-actions"><a href={`tel:+${String(site.consumerCare||'').replace(/\D/g,'')}`}><Phone size={14}/> Call</a><a href={wa} target="_blank" rel="noreferrer"><MessageCircle size={14}/> WhatsApp</a></div></div><div><h4>Explore</h4>{nav.slice(1).map(([to,label])=><Link key={to} to={to}>{label}</Link>)}</div><div><h4>Contact</h4><a href={`tel:+${String(site.phone||'').replace(/\D/g,'')}`}>{site.phone}</a><a href={`tel:+${String(site.consumerCare||'').replace(/\D/g,'')}`}>{site.consumerCare}</a><a href={site.mapUrl} target="_blank" rel="noreferrer">Open in Maps ↗</a></div></div><div className="container footer-bottom-premium"><span>© {new Date().getFullYear()} {site.shortBrand || site.brandName}</span><span>Since 1996</span></div></footer></div>;
}
